Feature/cpu test vertices
HKDAQ/TriggerApplication pull request #87
Opened 2020-11-05 17:42 UTC by federiconova

include CPU test vertices

2020-11-06 13:55 UTC, tdealtry requested changes
Thank you very much for this PR @federiconova! This is a huge chunk of important work!

2020-11-06 13:55 UTC, tdealtry commented on UserTools/test_vertices/test_vertices.cpp
> +      output_trigger_information.clear();
This variable seems to be filled, but not used
Is it possible to fill the `RecoInfo` with whatever information you have (e.g. position)?
This should go in at the `Execute()` stage I think (because we need to link reconstructed objects with triggered objects (and the global trigger index may not be the same as the test-vertices trigger index, e.g. if nhits has been run already)

2020-11-10 12:35 UTC, federiconova commented on configfiles/WCSimReaderTest/GPUProcessorConfig
> +DetectorFile inputfiles/detector.txt
fixed

2020-11-10 12:37 UTC, federiconova commented on configfiles/WCSimReaderTest/GPUProcessorConfig
> +#
fixed

2020-11-10 12:39 UTC, federiconova commented on configfiles/WCSimReaderTest/ToolsConfig
> +test_vertices1 test_vertices configfiles/WCSimReaderTest/GPUProcessorConfig
done

2020-11-10 12:43 UTC, federiconova commented on UserTools/test_vertices/test_vertices.h
> +  typedef unsigned short offset_t;
agreed. just for this case I don't want to change names as I want all variables and functions to be exact replicas in GPU-CUDA and CPU versions

2020-11-10 12:49 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +    }
done

2020-11-10 12:51 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +    CPU_test_vertices_execute(is->m_PMTid, m_time_int, &trigger_ns, &trigger_ts);
good point, thanks

2020-11-10 12:56 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +  m_time_int.reserve(2*(int)average_occupancy);
fixed

2020-11-10 12:59 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +  int n_PMTs_counter = 0;
I am aware of this delicate problem, and I know that written like this it works. So I wouldn't change it.

2020-11-10 13:00 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +    cerenkov_angle_water = acos(cerenkov_costheta);
probably. But I prefer to keep everythin identical to the GPU version. Anyway no one will modify those values unless they have a good reason.

2020-11-10 13:02 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +    costheta_cone_cut = m_costheta_cone_cut;
which two variables? Do you mean costheta_cone_cut amd m_costheta_cone_cut? Yes, that's to stick to the CUDA code which does not have the "m_" thing.

2020-11-10 13:02 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +  printf(" [2] detector contains %d PMTs \n", n_PMTs);
I just copied it over from the CUDA code (which does not have ToolDAQ logging)

2020-11-10 13:07 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +  if( !cylindrical_grid ){
done

2020-11-10 13:08 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +
ok

2020-11-10 13:10 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +  {
ok

2020-11-10 13:11 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +    if( min < 0 ){
ok

2020-11-10 13:13 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +      host_ids[i] = PMTids[i];
Sorry, don't understand the question. Of course we have to pass the PMT ids to the algorithm (?). And they *are* unsigned int (?).

2020-11-10 13:14 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +    if( !read_the_input_ToolDAQ(PMTid, time, &earliest_time) ){
Don't understand. The function read_the_input_ToolDAQ does return false.

2020-11-10 13:15 UTC, federiconova commented on UserTools/test_vertices/test_vertices.cpp
> +      output_trigger_information.clear();
this extra information is added in another pull request

2020-11-12 09:43 UTC, tdealtry commented on UserTools/test_vertices/test_vertices.h
> +  typedef unsigned short offset_t;
Ok yeah that makes sense

2020-11-12 09:49 UTC, tdealtry commented on UserTools/test_vertices/test_vertices.cpp
> +  int n_PMTs_counter = 0;
Ok, well as long as it works!

2020-11-12 10:17 UTC, tdealtry commented on UserTools/test_vertices/test_vertices.cpp
> +      host_ids[i] = PMTids[i];
You've got the PMT IDs stored in two objects. As `int` in `PMTids` and as `unsigned int` in `host_ids`
I guess this is another "CUDA does it like this" point. That's fine
I've made an issue to remind us to store PMTIds as `uint`s in the DataModel #92

2020-11-12 10:20 UTC, tdealtry commented on UserTools/test_vertices/test_vertices.cpp
> +    if( !read_the_input_ToolDAQ(PMTid, time, &earliest_time) ){
Sorry my bad

2020-11-12 10:22 UTC, tdealtry approved these changes
Thanks for this @federiconova Ready to merge now @brichards64

2020-11-13 17:03 UTC, merged