Feature/triggers comparison
HKDAQ/TriggerApplication pull request #88
Opened 2020-11-05 17:43 UTC by federiconova

add some functionalities to output triggers and compare outputs

2020-11-06 17:12 UTC, tdealtry requested changes
This follows on from #87 (so merge that first @brichards64!)

- The TriggerOutput looks like a nice simple output format that's going to be useful for analysing trigger performance. Thanks!
  - The TriggerComparison has got some nice tests too. Thanks again!
- The addition to WCSimReader of the interpose_interval is nice. We need to be careful to use it appropriately (because dark noise is a pain - we need to simulate complicated things in WCSim) but it looks like it will be useful for some studies

2020-11-06 17:12 UTC, tdealtry commented on UserTools/TriggersComparison/TriggersComparison.cpp
> +  h_triggertime_1 = new TH1F("h_triggertime_1","h_triggertime_1; time [ns];",(int)((max_trigger_time_1 - min_trigger_time_1 + 1)/timebinsize), min_trigger_time_1-timebinsize/2.,max_trigger_time_1+tim
Can you make the titles (axis or otherwise) of the triggertime/readouttime histograms a bit different? As it's hard to understand the difference unless you look at how they're filled in Execute()
From what I gleam, 
- h_triggertime is `Fill`ed once for every trigger
- h_readouttime starts at 0, and is set to 1 for any time that is "readout"
Is that about right?

2020-11-06 17:12 UTC, tdealtry commented on UserTools/TriggersComparison/TriggersComparison.cpp
> +      h_selections_intersection->Fill(1.,timebinsize);
This is a really great simple way to visulaise how different triggers are performing!
I've not thought very hard, but is it useful to have a value different to 0 for the case `!trigger1 && !trigger2)`?

2020-11-06 17:12 UTC, tdealtry commented on UserTools/TriggersComparison/README.md
> +# TriggersComparison
Can you describe the tool a bit?

2020-11-06 17:12 UTC, tdealtry commented on configfiles/TriggersComparison/README.md
> +# WCSimBONSAI toolchain configuration files
```suggestion
# TriggersComparison toolchain configuration files
```

2020-11-10 13:45 UTC, federiconova commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
yeah. I am not sure about what the critical points would be; this class was developed by Lukas Koch. I just made a function according to his instructions to avoid having to do the same thing over and over again.

2020-11-10 13:46 UTC, federiconova commented on UserTools/WCSimReader/WCSimReader.h
> +  float m_interpose_interval;
you are right

2020-11-10 14:09 UTC, federiconova commented on configfiles/TriggerOutput/README.md
> +# WCSimReaderTest toolchain configuration files
done

2020-11-10 14:13 UTC, federiconova commented on UserTools/TriggersComparison/TriggersComparison.cpp
> +  // Log("DEBUG: TriggersComparison::Initialise opening output file...", DEBUG2, m_verbose);
reverted

2020-11-10 14:16 UTC, federiconova commented on UserTools/TriggersComparison/TriggersComparison.cpp
> +  h_triggertime_1 = new TH1F("h_triggertime_1","h_triggertime_1; time [ns];",(int)((max_trigger_time_1 - min_trigger_time_1 + 1)/timebinsize), min_trigger_time_1-timebinsize/2.,max_trigger_time_1+tim
yes, it is correct. I think it was meant to be "read out time", with "read out" as a past tense, as in "this time has been read out". I renamed it.

2020-11-10 14:19 UTC, federiconova commented on UserTools/TriggersComparison/TriggersComparison.cpp
> +      h_selections_intersection->Fill(1.,timebinsize);
added

2020-11-10 14:20 UTC, federiconova commented on configfiles/TriggersComparison/README.md
> +# WCSimBONSAI toolchain configuration files
fixed

2020-11-10 14:22 UTC, federiconova commented on UserTools/TriggersComparison/README.md
> +# TriggersComparison
done

2020-11-12 10:34 UTC, tdealtry commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
From the [magic plot](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/IEEE754.png/550px-IEEE754.png) @ast0815 showed me when he was making TimeDelta 
At 1 ns, the precision is ~1E-8 ns
At 1E6 ns = 1ms, the precision is ~0.1 ns

So yeah, I guess adding a comment to be careful about 1 ms would be good

2020-11-12 11:19 UTC, ast0815 commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
This limitation has nothing to do with my class, but only with the number of digits you have in a float.

Also, this kind of method is not really needed. From TimeDelta.h:

https://github.com/HKDAQ/TriggerApplication/blob/6c1a456993f67e1ae3339790b8440af346ae845b/DataModel/TimeDelta.h#L22-L25

Here `t` is a TimeDelta object. This way there is no confusion about the unit of the `double`. I think this kind of floating point absolute time should only ever be used in time differences, i.e. when you know that the value is small, e.g.:

```
float t = (td1 - td2) / TimeDelta::ns;
```

Think about TimeDeltas ad times with a unit. When you want a unitless float, you need to divide by the unit.

2020-11-18 11:20 UTC, tdealtry commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
Thanks @ast0815 
So @federiconova I guess the thing to do is
- store things in doubles instead of floats in the output tree (note that at 10E12 ns = 1000 s there is still sub-nano second precision of the double. So this will work even for the 20 s SN simulations)
- get rid of this function
- use the division operator. e.g.
  ```
  the_readout_start_time = absolute_time(readout_start_time[i]);
  ```
  becomes
  ```
  the_readout_start_time = readout_start_time[i] / TimeDelta::ns;
  ```

2020-11-18 13:35 UTC, federiconova commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
Sorry, I am lost. In the context of this program, which is just meant to return an output not used by other modules but useful because it looks like the actual data output, I would like to have as an output variable the time of the trigger. I am confused by what "absolute", "relative" or "naive" mean.
I would like as an output the "full time": not the small time relative to the data header, not a difference, but a "full time" which can be directly compared with that from a different chunk of data (chunks that happen later have a bigger "full time").
Should that maybe be:
(d.m_short_time + d.m_long_time/TimeDelta::s_long_time_unit)/TimeDelta::ns;
? Notice all those constants are = 1.

2020-11-18 13:47 UTC, ast0815 commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
No. All those members are doubles and should not be divided by a TimeDelta (`TimeDelta::ns` is just a TimeDelta instance with the value of 1 ns.)

If all you want is a `double` with the time value in units of ns then `some_timedelta / TimeDelta::ns` should give you exactly that. Whether or not the `double` (or `float` if you want) is suitable to store that value at the precision you need, is then up to you.

2020-11-18 13:56 UTC, ast0815 commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
To calrify, TimeDelta implements the operators so that when you divide a TimeDelta by another TimeDelta, it automatically uses methods to do basically what you implemented yourself here. The result should be the same, but it would avoid duplicating code and ensure it will keep working in the future, in case the internal workings of TimeDelta change at any time.

2020-11-18 14:04 UTC, federiconova commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
ok, thank you

2020-11-18 15:29 UTC, tdealtry commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
Thanks @federiconova 
Just one more thing. Can you swap from float to double? (For this function, and the output tree) It's hopefully a quick change, and it will mean this tool will work for SN simulations, as well as order(ms) and smaller simulations like it does now with the float

2020-11-18 15:33 UTC, tdealtry commented
There's still some conflicts on this PR. You can use the website GUI way to do things as Ben showed in the meeting, or you can do things from the command line with a 
```
git pull <remote_name> master
```
where `remote_name` is whatever your `git remote -v` output says for `git@github.com:HKDAQ/TriggerApplication.git` (or the https equivalent*). If you don't have such a line, you can add it (naming it upstream is one convention, but can name it whatever you like)
```
git remote add upstream git@github.com:HKDAQ/TriggerApplication.git
```
(or the https equivalent)

*https://github.com/HKDAQ/TriggerApplication.git

2020-11-18 15:40 UTC, federiconova commented on UserTools/TriggerOutput/TriggerOutput.cpp
> +}
done

2020-11-18 15:56 UTC, federiconova commented
> There's still some conflicts on this PR. You can use the website GUI way to do things as Ben showed in the meeting, or you can do things from the command line with a
> 
> ```
> git pull <remote_name> master
> ```
> 
> where `remote_name` is whatever your `git remote -v` output says for `git@github.com:HKDAQ/TriggerApplication.git` (or the https equivalent*). If you don't have such a line, you can add it (naming it upstream is one convention, but can name it whatever you like)
> 
> ```
> git remote add upstream git@github.com:HKDAQ/TriggerApplication.git
> ```
> 
> (or the https equivalent)
> 
> *https://github.com/HKDAQ/TriggerApplication.git

I think I fixed it, but can you check if there are still conflicts?

2020-11-19 15:37 UTC, tdealtry commented
@federiconova the build is failing. It looks like `test_vertice.h` has multiple copies of most of the new lines (e.g. the following appears on line 48 & line 169)
```
typedef unsigned short offset_t;
```

2020-11-19 15:55 UTC, federiconova commented
> @federiconova the build is failing. It looks like `test_vertice.h` has multiple copies of most of the new lines (e.g. the following appears on line 48 & line 169)
> 
> ```
> typedef unsigned short offset_t;
> ```

ah, good thanks, I removed them.

2020-11-19 16:03 UTC, tdealtry commented
Build passed! Thanks @federiconova 
This is ready to go too @brichards64

2020-11-20 15:00 UTC, merged