Feature/test vertices return vertex
HKDAQ/TriggerApplication pull request #89
Opened 2020-11-05 17:43 UTC by federiconova

add vertex and direction information for SN triggering

2020-11-06 15:52 UTC, tdealtry requested changes
Thanks for this @federiconova. Going to be good to have this, so we can benchmark speed/resolution of test vertices against the other reconstruction tools

I've made a few pendatic comments on the config files, but the main one is whether the `test_vertices_reconstruction` tool is actually required (or if the filing of the `RecoInfo` can be done directly in the `test_vertices` tool)

2020-11-06 15:52 UTC, tdealtry commented on configfiles/WCSimBONSAI/WCSimReaderToolConfig
> +#infile FILES/vertical_neutrino.root
Can we keep this as a generic filename?
```suggestion
infile FILES/wcsim.root
```

2020-11-06 15:52 UTC, tdealtry commented on configfiles/WCSimBONSAI/ToolsConfig
> +#test_vertices1 test_vertices configfiles/WCSimBONSAI/GPUProcessorConfig
Can we make the tool config filename a bit clearer? e.g.
```suggestion
#test_vertices1 test_vertices configfiles/WCSimBONSAI/TestVerticesToolConfig
```
Obviously, use the same filename as in the WCSimReader toolchain!

2020-11-06 15:52 UTC, tdealtry commented on configfiles/WCSimBONSAI/ToolChainConfig
> +verbose 2 ## Verbosity level of ToolChain
```suggestion
verbose 4 ## Verbosity level of ToolChain
```
Can we keep the verbosity @ 4 for now? It's useful at the moment, since it says when a tool starts/stops its Initialise()/Execute()/Finalise() method (therefore very handy for knowing where to start when finding seg faults, etc.)

2020-11-06 15:52 UTC, tdealtry commented on UserTools/test_vertices_reconstruction/test_vertices_reconstruction.cpp
> +  //// YOUR CODE HERE
```suggestion
```

2020-11-06 15:52 UTC, tdealtry commented on UserTools/test_vertices_reconstruction/test_vertices_reconstruction.cpp
> +                                &(dout_direction[0]), &(dout_cone[0]), out_direction[5]);
Unless I'm missing something, there's no actual calculation* going on in this tool, and it's just taking the result from the trigger info structure. I suggested this in #87 too, but can this be added to the test_vertices tool instead? The major benefit will be not having to keep 2 configuration files in sync (the test_vertices one, and the test_vertices_reconstruction one)

*Other than the superfluous filling of the `m_in_Ts` and similar vectors (that is required for BONSAI, but not for this tool

2020-11-06 15:52 UTC, tdealtry commented on UserTools/test_vertices_reconstruction/README.md
> +test_vertices_reconstruction
A small description of what the tool does would be useful

2020-11-06 15:52 UTC, tdealtry commented on UserTools/test_vertices/test_vertices.h
> +  TimeDelta m_trigger_mask_window_post;
Thanks for adding these. I think it's a nice idea to use member variables with the same names in different tools - it will help reading/understanding/maintaining the tools a lot easier in the future.

Related to this - do `m_trigger_gate_up` and `m_trigger_gate_down` need to be defined as member variables still? It's still valid to use some `float`s in the `Initialise()` function, but maybe they can just be defined in that function?

2020-11-10 13:21 UTC, federiconova commented on configfiles/WCSimBONSAI/WCSimReaderToolConfig
> +#infile FILES/vertical_neutrino.root
done

2020-11-10 13:26 UTC, federiconova commented on configfiles/WCSimBONSAI/ToolsConfig
> +#test_vertices1 test_vertices configfiles/WCSimBONSAI/GPUProcessorConfig
done

2020-11-10 13:27 UTC, federiconova commented on configfiles/WCSimBONSAI/ToolChainConfig
> +verbose 2 ## Verbosity level of ToolChain
done

2020-11-10 13:30 UTC, federiconova commented on UserTools/test_vertices_reconstruction/test_vertices_reconstruction.cpp
> +  //// YOUR CODE HERE
done

2020-11-10 13:32 UTC, federiconova commented on UserTools/test_vertices_reconstruction/test_vertices_reconstruction.cpp
> +                                &(dout_direction[0]), &(dout_cone[0]), out_direction[5]);
on the other hand, you normally want to run test_vertices but no test_vertices_reconstruction, the latter being only used for the SN. And also splitting the two functions more closely parallels the nhits/BONSAI sequence. So I would prefer to keep it as is.

2020-11-10 13:33 UTC, federiconova commented on UserTools/test_vertices_reconstruction/README.md
> +test_vertices_reconstruction
done

2020-11-10 13:38 UTC, federiconova commented on UserTools/test_vertices/test_vertices.h
> +  TimeDelta m_trigger_mask_window_post;
good point, done

2020-11-12 11:44 UTC, tdealtry commented on UserTools/test_vertices_reconstruction/test_vertices_reconstruction.cpp
> +      out_direction[2] = 0;
Is this saving things as Euler angles? Not something to hold up the PR for, but I think we should move to using unit vectors, since they're much more intutive #93 

(I only used Euler angles when coding the ReconInfo class because that's what BONSAI uses and I wasn't sure of which of the ~12 conventions for converting to unit vectors it uses)

2020-11-12 11:49 UTC, tdealtry approved these changes
Thank @federiconova I'm still not convinced by the new tool, but lets go with it for now

2020-11-12 11:49 UTC, tdealtry commented on UserTools/test_vertices_reconstruction/test_vertices_reconstruction.cpp
> +                                &(dout_direction[0]), &(dout_cone[0]), out_direction[5]);
If this was doing an actual calculation, I'd agree with you (e.g. if test_vertices had returned a 5 m vertex, and this tool was refining that to e.g. ~1m resolution). But all the processing time has already been spent* in the test_vertices tool. 

* or at least will be when we get rid of the horrible loop over all hits for every trigger, when we move to the new parallel setup

I think lets merge this now, but we might decide to move things into test_vertices tool later

2020-11-18 11:22 UTC, tdealtry commented
@federiconova in case you missed it, merging #87 has caused a conflict in this PR
(@brichards64 assigning labels doesn't automatically send emails out, so a little comment to say there's now a conflict is helpful, because I totally missed it!)

2020-11-18 13:39 UTC, federiconova commented
> @federiconova in case you missed it, merging #87 has caused a conflict in this PR
> (@brichards64 assigning labels doesn't automatically send emails out, so a little comment to say there's now a conflict is helpful, because I totally missed it!)

2020-11-18 13:40 UTC, federiconova commented
> @federiconova in case you missed it, merging #87 has caused a conflict in this PR
> (@brichards64 assigning labels doesn't automatically send emails out, so a little comment to say there's now a conflict is helpful, because I totally missed it!)

Sorry, what is the conflict? I can't find it!

2020-11-18 14:02 UTC, tdealtry commented
<img width="480" alt="image" src="https://user-images.githubusercontent.com/11757479/99539850-a8e7b700-29a6-11eb-80ba-92d58a01d33b.png">

2020-11-18 16:31 UTC, federiconova commented
> <img alt="image" width="480" src="https://user-images.githubusercontent.com/11757479/99539850-a8e7b700-29a6-11eb-80ba-92d58a01d33b.png">

I think it's fixed but can you check?

2020-11-19 15:20 UTC, tdealtry commented
That's got it. Thanks @federiconova 
Ready to go @brichards64

2020-11-21 14:36 UTC, merged