Updateframework
HKDAQ/TriggerApplication pull request #90
Opened 2020-11-09 18:10 UTC by brichards64

2020-11-10 12:45 UTC, tdealtry requested changes
I've skimmed through the code - added some comments (mainly missing documentation)

I've got it to compile with FLOWER & BONSAI - see #91 (which should merge into this branch)

Not tested that results are equivalent to the master branch yet - will hopefully be able to do that this afternoon

For future reference - it's good to split PRs up if possible e.g. updating the docs folder could have been a separate PR (723 files changed!!!!!)

2020-11-10 12:45 UTC, tdealtry commented on Doxyfile
> +# Doxyfile 1.8.5
With this, you can probably now remove `docs/doxygen.config`

2020-11-10 12:45 UTC, tdealtry commented on UserTools/newTool.sh
> +
```suggestion
    echo "Valid tools templates are: <BLANK> DynamicMultiThread MultiThread ServiceAdd Thread ZMQMultiThread"
```

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolDynamicMultiThread.h
> +  unsigned long m_threadnum;
Can you doxy these?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolDynamicMultiThread.h
> + * This is a balnk template for a Tool used by the script to generate a new custom tool. Please fill out the descripton and author information.
Can you expand this? i.e. say what `MyToolDynamicMultiThread` does that `MyTool` doesn't
Probably also want some documentation somewhere (template/README.md, or the base level README.md) saying how to choose the tool template for a given use case

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolMultiThread.h
> +  int m_freethreads;
Can you doxy this?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolMultiThread.h
> + * This is a balnk template for a Tool used by the script to generate a new custom tool. Please fill out the descripton and author information.
Can you expand this?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolServiceAdd.h
> +  int m_port;
Can you doxy this?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolServiceAdd.h
> + * This is a balnk template for a Tool used by the script to generate a new custom tool. Please fill out the descripton and author information.
Expand this?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolThread.h
> + * This is a balnk template for a Tool used by the script to generate a new custom tool. Please fill out the descripton and author information.
Expand this?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolThread.h
> +  MyToolThread_args* args;
Doxy?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolZMQMultiThread.h
> + * This is a balnk template for a Tool used by the script to generate a new custom tool. Please fill out the descripton and author information.
Expand?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolZMQMultiThread.h
> +  int m_freethreads;
Doxy?

2020-11-10 12:45 UTC, tdealtry commented on UserTools/template/MyToolZMQMultiThread.h
> +  zmq::pollitem_t items[2];
```suggestion
  zmq::pollitem_t m_items[2]; 
```

2020-11-10 12:45 UTC, tdealtry commented on CMakeLists.txt
> +cmake_minimum_required (VERSION 2.6)
Could you add to the README.md how to compile with cmake?

2020-11-10 16:20 UTC, brichards64 commented on DataModel/Utilities.h
> +struct Thread_args{
done

2020-11-10 16:20 UTC, brichards64 commented on UserTools/newTool.sh
> +
done made it dynamic to the template folder

2020-11-10 16:20 UTC, brichards64 commented on UserTools/template/MyToolDynamicMultiThread.h
> +  unsigned long m_threadnum;
done

2020-11-10 16:20 UTC, brichards64 commented on UserTools/template/MyToolZMQMultiThread.h
> + * This is a balnk template for a Tool used by the script to generate a new custom tool. Please fill out the descripton and author information.
done

2020-11-10 16:21 UTC, brichards64 commented on UserTools/template/MyToolZMQMultiThread.h
> +  int m_freethreads;
done

2020-11-10 16:21 UTC, brichards64 commented on CMakeLists.txt
> +cmake_minimum_required (VERSION 2.6)
cmake looks very broken right now. not sure we should wait for it

2020-11-10 16:22 UTC, brichards64 commented on UserTools/template/MyToolZMQMultiThread.h
> +  zmq::pollitem_t items[2];
i know its a member variable but for these poll items i prefer it without the m as its clearer to me. I dont know how strongly you feel about this

2020-11-10 16:22 UTC, brichards64 commented on UserTools/template/MyToolThread.h
> +  MyToolThread_args* args;
done

2020-11-10 16:22 UTC, brichards64 commented on Doxyfile
> +# Doxyfile 1.8.5
dont follow

2020-11-10 16:23 UTC, brichards64 commented on DataModel/DataModel.h
> + * Contact: b.richards@qmul.ac.uk
yeh..... I guess ill do it in the core framework eventually on next realease. i still have the email so its ok for now

2020-11-11 09:05 UTC, tdealtry commented on Doxyfile
> +# Doxyfile 1.8.5
Doxyfile & docs/doxygen.config are the same file (pretty much - Doxyfile has a newer version, and the project name is ToolDAQFramework rather than TriggerApplication). We probably don't need both

2020-11-11 09:13 UTC, tdealtry commented on CMakeLists.txt
> +cmake_minimum_required (VERSION 2.6)
Yeah waiting until it works makes sense

2020-11-11 09:20 UTC, tdealtry commented on UserTools/template/MyToolZMQMultiThread.h
> +  zmq::pollitem_t items[2];
Personally I'd prefer not using normal snake case for member variables - it just makes it easier to read (instead of having to check where `items` is defined in the function, then being confused that it's not). We could have a different convention for variables that are part of the threading. e.g.
- `p_items` (p for parallel)
- `t_items` (t for thread)
- `TItems`
- ...

2020-11-11 10:05 UTC, tdealtry approved these changes
Test of the WCSimBONSAI toolchain (100 10 MeV electrons) produces identical results. This PR now ready to go

2020-11-11 10:45 UTC, merged